DELETE FROM TB_DOCUMENTO_MANIPULACAO WHERE REGISTRO > 0;
DELETE FROM tb_documento_digitalizacao WHERE REGISTRO > 0;
DELETE FROM tb_subserie_indice_valor WHERE registro > 0;
DELETE FROM tb_subserie_indice WHERE registro > 0;
DELETE FROM TB_DOCUMENTO WHERE REGISTRO > 0;
DELETE FROM tb_prazo_guarda WHERE REGISTRO > 0;
DELETE FROM tb_caixa WHERE REGISTRO > 0;
DELETE FROM tb_subserie_usuario WHERE SUBSERIE > 0;
DELETE FROM tb_subserie WHERE registro > 0;
DELETE FROM tb_serie WHERE REGISTRO > 0;
DELETE FROM tb_subclasse WHERE REGISTRO > 0;
DELETE FROM TB_CLASSE WHERE REGISTRO > 0;
DELETE FROM TB_PRATELEIRA WHERE REGISTRO > 0;
DELETE FROM TB_ESTANTE WHERE REGISTRO > 0;
DELETE FROM tb_corredor WHERE REGISTRO > 0;
DELETE FROM TB_USUARIO_GRUPO WHERE USUARIO <> 1;
DELETE FROM tb_usuario WHERE registro <> 1;




